---
title: "ITR_PD"
author: "Cuong Pham"
date: "2024-12-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r echo=FALSE}
#load the library
library(xtable)
library(dplyr)
library(lme4) #mixed model
library(kableExtra)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(progress)

#import data 
iv.dat2a = readRDS(file = "clean_data_outcome_change.RDS")
colnames(iv.dat2a)[25] = "Time_since_first_Levo" 


```



## Summary of the data 

```{r}

#these codes create 

tab_90 <- summarize_data(
  iv.dat2a,
  filter_condition = quote(Time_baseline_2nd_line <= 90)
)

tab_180 <- summarize_data(
  iv.dat2a,
  filter_condition = quote(Time_baseline_2nd_line <= 180 & Time_baseline_2nd_line > 90)
)

table1.paper = cbind(t(tab_90), t(tab_180))
colnames(table1.paper) = c("90 day cutoff", "added")

table1.paper %>% kable()
```



## Construction of the instrumental variable

We construct the instrumental variable using all the data set. 

```{r echo=FALSE}
#remove the center with only one or two patients
center = iv.dat2a %>% group_by(cno) %>% summarise(cno.pct = mean(A == 1), no.patients = n()) %>% filter(no.patients > 2)
iv.dat2a = iv.dat2a %>% filter(cno %in% center$cno) 


iv.dat2a_scaled <- iv.dat2a
iv.dat2a_scaled[, c("updrs_1", "updrs_2", "updrs_3", "age.2nd", "time_from_diagnosis.2nd", "bmi", "levodopa_dose.2nd", "Time_since_first_Levo")] <- scale(iv.dat2a[, c("updrs_1", "updrs_2", "updrs_3", "age.2nd", "time_from_diagnosis.2nd", "bmi", "levodopa_dose.2nd", "Time_since_first_Levo")])
#fitting the mixed model



mixed.model = glmer(as.factor(A) ~ updrs_1 + updrs_2 + updrs_3 + 
                    age.2nd + gender + time_from_diagnosis.2nd + bmi + nausea + dys + fluc + ortho + sleep +
                      levodopa_dose.2nd + Time_since_first_Levo +(1|cno), data = iv.dat2a_scaled, family = binomial, control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 1e5)))


#summary(mixed.model)


rand_effects = ranef(mixed.model)
rand_effects = rand_effects$cno


median.rand = median(rand_effects$`(Intercept)`)



rand_effects$Z = ifelse(rand_effects$`(Intercept)` >= median.rand,1,-1)

rand_effects$cno = row.names(rand_effects)

iv.dat2a = left_join(iv.dat2a, rand_effects[,c("Z", "cno")], by = "cno")

#proportion of compliance


#mean(iv.dat2a$A == 1 & iv.dat2a$Z == 1) - mean(iv.dat2a$A == 1 & iv.dat2a$Z == - 1)

cutoff = c(90, 150, 180, 200)

n.sample = NA
compliance.prob = NA
for(i in 1:length(cutoff)){

    temp.dat =  iv.dat2a %>% filter(Time_baseline_2nd_line < cutoff[i])
   n.sample[i] = temp.dat %>% nrow()
  
   compliance.prob[i] = mean(temp.dat$A == 1 & temp.dat$Z == 1)/mean(temp.dat$Z == 1) - mean(temp.dat$A == 1 & temp.dat$Z == -1)/mean(temp.dat$Z == -1)
}

plot(x = n.sample, y = compliance.prob )
```


```{r}

logit.mod = glm(as.factor(A) ~ Z, data = iv.dat2a[iv.dat2a$Time_baseline_2nd_line <= 90,], family = binomial())
summary(logit.mod)
```


```{r echo = FALSE}
barplot(sort(rand_effects$`(Intercept)`))
abline(h = median.rand)
```


## UPDRS III


```{r}
 total_iterations = 500
  pb <- progress_bar$new(
    format = "[:bar] :current/:total :percent eta: :eta",
    total = total_iterations
  )
  
  temp_dat = iv.dat2a %>% filter(Time_baseline_2nd_line <= 180)
  
  all_results_updrs = list()

  for(i in 1:total_iterations) {
   
    res = fit.iv.owl(itr_formula = ~ updrs_1 + updrs_2 + updrs_3 + time_from_diagnosis.2nd + levodopa_dose.2nd + gender + age.2nd + bmi + dys + fluc + nausea + sleep + Time_since_first_Levo,
           iv_formula =  ~ updrs_1 + updrs_2 + updrs_3 + time_from_diagnosis + levodopa_dose + gender + age + bmi +Time_since_first_Levo, 
           trt_formula = ~ updrs_1 + updrs_2 + updrs_3 + time_from_diagnosis.2nd + levodopa_dose.2nd + gender + age.2nd + bmi + Time_since_first_Levo,
           mean_formula = ~ updrs_1 +  updrs_2 + updrs_3 + time_from_diagnosis.2nd + levodopa_dose.2nd +
             gender + age.2nd  + bmi  + Time_since_first_Levo, method = "owl",
           dat = temp_dat, trt ="A", iv = "Z", outcome = "outcome_updrs3", seed = i, minimize = T, center.outcome = T )
    
    all_results_updrs[[i]] <- res
    
    pb$tick()
  }
  
 # all_results_updrs[[1]]
calculate.statistics(all_results = all_results_updrs, mean)

```


```{r}

extract_number <- function(x) {
  num_str <- gsub("\\s*\\(.*?\\)", "", x)  # Remove the part inside the parentheses
  as.numeric(num_str)  # Convert the remaining string to a numeric value
}


sel.cov = c("updrs_1", "updrs_2" , "updrs_3" , "time_from_diagnosis.2nd" , "levodopa_dose.2nd",
            "gender" , "age.2nd" ,"bmi", "dys","fluc", "nausea", "sleep", "Time_since_first_Levo")

#sel.cov = c("updrs_1", "updrs_2" , "updrs_3" , "time_from_diagnosis.2nd" , "levodopa_dose.2nd",
#            "gender" , "age.2nd" ,"bmi", "dys","fluc", "nausea", "sleep")

outcome = "outcome_updrs3"

updrs.opt = matrix(nrow = length(cutoff), ncol = 3)
DR.dist = list()
updrs.opt.owl =  matrix(nrow = length(cutoff), ncol = 3)
DR.dist.owl = list()
svm.coefficient.iv.owl = matrix(nrow = length(sel.cov) + 1, ncol = length(cutoff))
svm.coefficient.owl = svm.coefficient.iv.owl 

#iv.dat2a = iv.dat2a %>% filter(!(patno %in% remove.patno))
#iv.dat2a = iv.dat2a %>% filter(outcome_updrs3 >= 5 & outcome_updrs3 <= 40 )

for(i in 1:length(cutoff)){
  
    print(cutoff[i])
 temp.result = sim.updrs.func(FUN = fit.iv.owl.bt.ls1.postcept , dat = iv.dat2a %>% filter(Time_baseline_2nd_line <= cutoff[i]), outcome.col = outcome, kernel = "linear", covariates = sel.cov, plot.title = "UPDRS I", lb = 0, logistic = T)

   #temp.result.owl = sim.updrs.func(FUN = fit.owl.mr.sim, dat = iv.dat2a %>% filter(Time_baseline_2nd_line <= cutoff[i]), outcome.col = outcome, kernel = "linear", covariates = sel.cov, plot.title = "UPDRS I", lb = 0.1, logistic = T)
   
   temp.result.owl = sim.updrs.func(FUN = fit.owl.bt.ls1.postcept, dat = iv.dat2a %>% filter(Time_baseline_2nd_line <= cutoff[i]), outcome.col = outcome, kernel = "linear", covariates = sel.cov, plot.title = "UPDRS I", lb = 0, logistic = T)
   
updrs.opt[i,] = temp.result$MR 
DR.dist[[i]] = temp.result$DR.est
svm.coefficient.iv.owl[,i] = temp.result$decision.coef
svm.coefficient.owl[,i] = temp.result.owl$decision.coef
 
 updrs.opt.owl[i,] = temp.result.owl$MR
 DR.dist.owl[[i]] = temp.result.owl$DR.est
 
}


#updrs.opt = updrs.opt[,c(2,4,6)] 
colnames(updrs.opt)= c("Optimal", "MAOB only", "DRA only")
updrs.opt = as.data.frame(updrs.opt)
updrs.opt$cut.off.day = cutoff
updrs.opt$Optimal.OWL = updrs.opt.owl[,1]
updrs.opt = updrs.opt %>% select(cut.off.day, Optimal.OWL, Optimal, `MAOB only`, `DRA only`)
updrs.opt$Sample.size = n.sample

rownames(svm.coefficient.iv.owl) = c("intercept", sel.cov)
rownames(svm.coefficient.owl) = c("Intercept", sel.cov)
colnames(updrs.opt) = c("Cut off day",  "Optimal OWL", "Optimal",  "MAOB only", "DRA only", "Sample Size")

df.plt = data.frame(cutoff = cutoff, sample.size = n.sample, value.function = c(extract_number(updrs.opt[,"Optimal"]), extract_number(updrs.opt[,"Optimal OWL"]), extract_number(updrs.opt[,"MAOB only"]), extract_number(updrs.opt[,"DRA only"])) ,regime = c(rep("Optimal", nrow(updrs.opt) ), rep("Optimal OWL", nrow(updrs.opt) ), rep("MAOB", nrow(updrs.opt)), rep("DRA", nrow(updrs.opt))))

coef.tab = cbind(svm.coefficient.iv.owl, svm.coefficient.owl)
colnames(coef.tab) = c("90 days", "180 days", "90 days", "180 days") 

```
